-- MySQL Script generated by MySQL Workbench
-- 03/09/16 09:49:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema FiND
-- -----------------------------------------------------
-- My database created from ERD
-- 

-- -----------------------------------------------------
-- Schema FiND
--
-- My database created from ERD
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FiND` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema new_schema2
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema new_schema3
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema new_schema4
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema new_schema5
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema new_schema6
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema new_schema7
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema new_schema8
-- -----------------------------------------------------
USE `FiND` ;

-- -----------------------------------------------------
-- Table `FiND`.`Publications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FiND`.`Publications` (
  `PublicationID` VARCHAR(8) NOT NULL,
  `PublicationTitle` VARCHAR(200) NULL,
  `PublicationQuery` VARCHAR(200) NULL,
  `PublicationYear` DATE NULL,
  PRIMARY KEY (`PublicationID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FiND`.`Publishers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FiND`.`Publishers` (
  `PublisherID` VARCHAR(8) NOT NULL,
  `PublisherName` VARCHAR(450) NOT NULL,
  `PublisherLocation` VARCHAR(200) NULL,
  PRIMARY KEY (`PublisherID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FiND`.`Journals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FiND`.`Journals` (
  `JournalID` VARCHAR(8) NOT NULL,
  `JournalTitle` VARCHAR(100) NOT NULL,
  `PublisherID` VARCHAR(8) NOT NULL,
  `AuthorID` INT NOT NULL,
  PRIMARY KEY (`JournalID`),
  INDEX `PublisherID_idx` (`PublisherID` ASC),
  CONSTRAINT `fk_Journals_JournalID`
    FOREIGN KEY (`JournalID`)
    REFERENCES `FiND`.`Publications` (`PublicationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Journals_PublisherID`
    FOREIGN KEY (`PublisherID`)
    REFERENCES `FiND`.`Publishers` (`PublisherID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FiND`.`JournalArticles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FiND`.`JournalArticles` (
  `JournalArticleID` VARCHAR(10) NOT NULL,
  `JournalArticleName` VARCHAR(45) NOT NULL,
  `PublishedYear` DATE NOT NULL,
  `AuthorID` INT NOT NULL,
  `AuthorList` VARCHAR(45) NOT NULL,
  `Volume` VARCHAR(5) NULL,
  `Issue` INT NULL,
  `Pages` INT NOT NULL,
  `JournalID` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`JournalArticleID`),
  UNIQUE INDEX `JournalArticleID_UNIQUE` (`JournalArticleID` ASC),
  INDEX `JournalID_idx` (`JournalID` ASC),
  CONSTRAINT `fk_JournalArticles_JournalArticleID`
    FOREIGN KEY (`JournalArticleID`)
    REFERENCES `FiND`.`Publications` (`PublicationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_JournalArticles_JournalID`
    FOREIGN KEY (`JournalID`)
    REFERENCES `FiND`.`Journals` (`JournalID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FiND`.`Books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FiND`.`Books` (
  `BookID` VARCHAR(8) NOT NULL,
  `BookTitle` VARCHAR(100) NOT NULL,
  `PublishedYear` DATE NOT NULL,
  `AuthorList` INT NOT NULL,
  `ISBN` VARCHAR(45) NULL,
  `PublisherID` VARCHAR(8) NOT NULL,
  `Pages` VARCHAR(20) NULL,
  `Language` VARCHAR(45) NULL,
  `Abstract` MEDIUMTEXT NULL,
  `Keywords` VARCHAR(1000) NULL,
  `SourceURL` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`BookID`),
  INDEX `PublisherID_idx` (`PublisherID` ASC),
  CONSTRAINT `fk_Books_BookID`
    FOREIGN KEY (`BookID`)
    REFERENCES `FiND`.`Publications` (`PublicationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Books_PublisherID`
    FOREIGN KEY (`PublisherID`)
    REFERENCES `FiND`.`Publishers` (`PublisherID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FiND`.`BookArticles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FiND`.`BookArticles` (
  `BookArticleID` VARCHAR(8) NOT NULL,
  `BookArticleTitle` VARCHAR(100) NOT NULL,
  `PublishedYear` DATE NOT NULL,
  `AuthorList` INT NOT NULL,
  `ISBN` VARCHAR(45) NULL,
  `PublisherID` VARCHAR(8) NOT NULL,
  `Pages` VARCHAR(20) NULL,
  `Language` VARCHAR(45) NULL,
  `ArticleType` VARCHAR(45) NOT NULL,
  `Abstract` MEDIUMTEXT NULL,
  `Keywords` VARCHAR(1000) NULL,
  `SourceURL` VARCHAR(100) NOT NULL,
  `BookID` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`BookArticleID`),
  INDEX `BookID_idx` (`BookID` ASC),
  INDEX `PublisherID_idx` (`PublisherID` ASC),
  CONSTRAINT `fk_BookArticles_BookArticleID`
    FOREIGN KEY (`BookArticleID`)
    REFERENCES `FiND`.`Publications` (`PublicationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BookArticles_BookID`
    FOREIGN KEY (`BookID`)
    REFERENCES `FiND`.`Books` (`BookID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BookArticles_PublisherID`
    FOREIGN KEY (`PublisherID`)
    REFERENCES `FiND`.`Publishers` (`PublisherID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FiND`.`Conferences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FiND`.`Conferences` (
  `ConferenceID` VARCHAR(8) NOT NULL,
  `ConferenceTitle` VARCHAR(100) NOT NULL,
  `PublishedYear` DATE NOT NULL,
  `PublishedMonth` DATE NOT NULL,
  `AuthorList` INT NOT NULL,
  `Language` VARCHAR(45) NULL,
  `Location` VARCHAR(45) NOT NULL,
  `Abstract` MEDIUMTEXT NULL,
  `Keywords` VARCHAR(1000) NULL,
  `SourceURL` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ConferenceID`),
  CONSTRAINT `fk_Conferences_ConferenceID`
    FOREIGN KEY (`ConferenceID`)
    REFERENCES `FiND`.`Publications` (`PublicationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FiND`.`SciNTechReports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FiND`.`SciNTechReports` (
  `ReportID` VARCHAR(8) NOT NULL,
  `ReportTitle` VARCHAR(100) NOT NULL,
  `PublishedYear` DATE NOT NULL,
  `AuthorList` INT NOT NULL,
  `PublisherID` VARCHAR(8) NOT NULL,
  `Language` VARCHAR(45) NULL,
  `AffiliationName` VARCHAR(1000) NOT NULL,
  `Abstract` MEDIUMTEXT NULL,
  `Keywords` VARCHAR(1000) NULL,
  `SourceURL` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ReportID`),
  INDEX `PublisherID_idx` (`PublisherID` ASC),
  CONSTRAINT `fk_SciNTechReports_ReportID`
    FOREIGN KEY (`ReportID`)
    REFERENCES `FiND`.`Publications` (`PublicationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SciNTechReports_PublisherID`
    FOREIGN KEY (`PublisherID`)
    REFERENCES `FiND`.`Publishers` (`PublisherID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FiND`.`DessertationsNThesis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FiND`.`DessertationsNThesis` (
  `DissNThesisID` VARCHAR(8) NOT NULL,
  `DissNThesisTitle` VARCHAR(100) NOT NULL,
  `PublishedYear` DATE NOT NULL,
  `AuthorList` INT NOT NULL,
  `AffiliationName` VARCHAR(1000) NOT NULL,
  `Language` VARCHAR(45) NULL,
  `References` VARCHAR(45) NULL,
  `PhdMasters` TINYINT(1) NOT NULL,
  `Abstract` MEDIUMTEXT NULL,
  `Keywords` VARCHAR(1000) NULL,
  `SourceURL` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`DissNThesisID`),
  CONSTRAINT `fk_DissNThesis_DissNThesisID`
    FOREIGN KEY (`DissNThesisID`)
    REFERENCES `FiND`.`Publications` (`PublicationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FiND`.`Authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FiND`.`Authors` (
  `AuthorID` INT NOT NULL AUTO_INCREMENT,
  `AuthorsLastName` VARCHAR(45) NOT NULL,
  `AuthorsFirstName` VARCHAR(45) NOT NULL,
  `AuthorsMiddleInit` VARCHAR(45) NULL,
  `AffiliationName` VARCHAR(1000) NULL,
  PRIMARY KEY (`AuthorID`),
  UNIQUE INDEX `AuthorID_UNIQUE` (`AuthorID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FiND`.`PublicationAuthors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FiND`.`PublicationAuthors` (
  `PublicationID` VARCHAR(8) NOT NULL,
  `AuthorID` INT NOT NULL,
  INDEX `authourID_idx` (`AuthorID` ASC),
  CONSTRAINT `fk_PublicationAuthors_AuthorID`
    FOREIGN KEY (`AuthorID`)
    REFERENCES `FiND`.`Authors` (`AuthorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PublicationAuthors_PublicationID`
    FOREIGN KEY (`PublicationID`)
    REFERENCES `FiND`.`Publications` (`PublicationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FiND`.`PublicationReferences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FiND`.`PublicationReferences` (
  `PublicationID` VARCHAR(8) NOT NULL,
  `ReferenceID` VARCHAR(8) NOT NULL,
  INDEX `ReferenceID_idx` (`ReferenceID` ASC),
  CONSTRAINT `fk_PublicationReferences_PublicationID`
    FOREIGN KEY (`PublicationID`)
    REFERENCES `FiND`.`Publications` (`PublicationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PublicationReferences_ReferenceID`
    FOREIGN KEY (`ReferenceID`)
    REFERENCES `FiND`.`Publications` (`PublicationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
